"""tablas iniciales

Revision ID: 0a18a24c8531
Revises: 
Create Date: 2026-05-08 19:24:56.769566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

revision: str = '0a18a24c8531'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sessions',
    sa.Column('ses_id', sa.Integer(), nullable=False),
    sa.Column('ses_usuario', sa.String(length=100), nullable=False),
    sa.Column('ses_fecha', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('ses_id')
    )
    op.create_table('Clients',
    sa.Column('cli_id', sa.Integer(), nullable=False),
    sa.Column('cli_name', sa.String(length=100), nullable=False),
    sa.Column('cli_phone', sa.String(length=10), nullable=False),
    sa.Column('cli_email', sa.String(length=100), nullable=False),
    sa.Column('cli_date_mod', sa.DateTime(), nullable=True),
    sa.Column('ses_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ses_id'], ['Sessions.ses_id'], ),
    sa.PrimaryKeyConstraint('cli_id'),
    sa.UniqueConstraint('cli_email'),
    sa.UniqueConstraint('cli_phone')
    )
    op.create_table('Service',
    sa.Column('srv_id', sa.Integer(), nullable=False),
    sa.Column('srv_name', sa.String(length=100), nullable=False),
    sa.Column('srv_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ses_id', sa.Integer(), nullable=True),
    sa.Column('srv_date_mod', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ses_id'], ['Sessions.ses_id'], ),
    sa.PrimaryKeyConstraint('srv_id'),
    sa.UniqueConstraint('srv_name')
    )
    op.create_table('users',
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('usr_username', sa.String(length=100), nullable=False),
    sa.Column('usr_password', sa.String(length=255), nullable=False),
    sa.Column('usr_rol', sa.String(length=50), nullable=False),
    sa.Column('ses_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ses_id'], ['Sessions.ses_id'], ),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_username')
    )
    op.create_table('Vehicles',
    sa.Column('veh_id', sa.Integer(), nullable=False),
    sa.Column('veh_plate', sa.String(length=10), nullable=False),
    sa.Column('veh_brand', sa.String(length=50), nullable=False),
    sa.Column('veh_model', sa.String(length=50), nullable=False),
    sa.Column('veh_year', sa.Integer(), nullable=False),
    sa.Column('cli_id', sa.Integer(), nullable=False),
    sa.Column('ses_id', sa.Integer(), nullable=False),
    sa.Column('cli_date_mod', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cli_id'], ['Clients.cli_id'], ),
    sa.ForeignKeyConstraint(['ses_id'], ['Sessions.ses_id'], ),
    sa.PrimaryKeyConstraint('veh_id'),
    sa.UniqueConstraint('veh_plate')
    )
    op.create_table('Orders',
    sa.Column('ord_id', sa.Integer(), nullable=False),
    sa.Column('ord_date', sa.DateTime(), nullable=True),
    sa.Column('ord_status', sa.String(length=50), nullable=False),
    sa.Column('ord_urgency', sa.String(length=50), nullable=False),
    sa.Column('ses_id', sa.Integer(), nullable=False),
    sa.Column('veh_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ses_id'], ['Sessions.ses_id'], ),
    sa.ForeignKeyConstraint(['veh_id'], ['Vehicles.veh_id'], ),
    sa.PrimaryKeyConstraint('ord_id')
    )
    op.create_table('ServiceOrders',
    sa.Column('srv_ord_id', sa.Integer(), nullable=False),
    sa.Column('ord_id', sa.Integer(), nullable=False),
    sa.Column('srv_id', sa.Integer(), nullable=False),
    sa.Column('ords_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ords_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ses_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ord_id'], ['Orders.ord_id'], ),
    sa.ForeignKeyConstraint(['ses_id'], ['Sessions.ses_id'], ),
    sa.ForeignKeyConstraint(['srv_id'], ['Service.srv_id'], ),
    sa.PrimaryKeyConstraint('srv_ord_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones',
    sa.Column('ses_id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('usuario_id', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('fecha_inicio', oracle.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('ses_id', name=op.f('sys_c008316')),
    oracle_tablespace='USERS'
    )

    # ### end Alembic commands ###