"""objetos PL/SQL: vistas, SP, función, triggers, tabla permisos

NOTA sobre quoting:
- Tablas creadas por SQLAlchemy (0a18a24c8531): "Vehicles", "Orders",
  "ServiceOrders", "Service", "Clients", "Sessions", "users"
  → SIEMPRE con comillas dobles Oracle: "TablaName"
- Tablas creadas con op.execute(): permisos_rol
  → SIN comillas (Oracle la crea como PERMISOS_ROL)

NOTA sobre :NEW / :OLD en triggers:
- SQLAlchemy text() interpreta :param como bind variable.
- Escapar con \\:NEW → SQLAlchemy ve \\: como colon literal.

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-05-12 08:30:00.000000

"""
from typing import Sequence, Union

from alembic import op

revision: str = 'b2c3d4e5f6a7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _safe(sql: str) -> None:
    try:
        op.execute(sql)
    except Exception as e:
        print(f"Saltando: {str(e)[:120]}")


def upgrade() -> None:
    # --- Tabla de roles con permisos por bitmask ---
    # Cada rol tiene un bitmask de permisos (1=lectura, 2=escritura, etc.).
    # Creada con op.execute() directo → Oracle la almacena como PERMISOS_ROL (uppercase, sin comillas).
    _safe("""
        CREATE TABLE permisos_rol (
            rol_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            rol_nombre VARCHAR2(50) NOT NULL UNIQUE,
            permiso_bitmask NUMBER(3) NOT NULL
        )
    """)

    # --- Datos iniciales de roles ---
    # admin=255 (todos los bits), mecanico=7, recepcion=3, cliente=1.
    _safe("INSERT INTO permisos_rol (rol_nombre, permiso_bitmask) VALUES ('admin', 255)")
    _safe("INSERT INTO permisos_rol (rol_nombre, permiso_bitmask) VALUES ('mecanico', 7)")
    _safe("INSERT INTO permisos_rol (rol_nombre, permiso_bitmask) VALUES ('recepcion', 3)")
    _safe("INSERT INTO permisos_rol (rol_nombre, permiso_bitmask) VALUES ('cliente', 1)")

    # --- Función: fn_tiene_permiso ---
    # Verifica si un rol tiene un permiso específico usando BITAND.
    # Retorna 1 si tiene el permiso, 0 si no (o si el rol no existe).
    _safe("""
        CREATE OR REPLACE FUNCTION fn_tiene_permiso(
            p_rol IN VARCHAR2,
            p_permiso IN NUMBER
        ) RETURN NUMBER
        IS
            v_mask NUMBER(3);
        BEGIN
            SELECT permiso_bitmask INTO v_mask
            FROM permisos_rol
            WHERE rol_nombre = p_rol;
            IF BITAND(v_mask, p_permiso) = p_permiso THEN
                RETURN 1;
            ELSE
                RETURN 0;
            END IF;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RETURN 0;
        END fn_tiene_permiso;
    """)

    # --- Función: fn_calcular_total_orden ---
    # Suma el total de todos los servicios asociados a una orden.
    # Retorna 0 si la orden no tiene servicios o no existe.
    _safe("""
        CREATE OR REPLACE FUNCTION fn_calcular_total_orden(
            p_ord_id IN NUMBER
        ) RETURN NUMBER
        IS
            v_total NUMBER(10,2);
        BEGIN
            SELECT COALESCE(SUM(ords_total), 0) INTO v_total
            FROM "ServiceOrders"
            WHERE ord_id = p_ord_id;
            RETURN v_total;
        END fn_calcular_total_orden;
    """)

    # --- Procedimiento: sp_cerrar_orden ---
    # Cierra una orden si cumple las condiciones:
    #   1. No está ya cerrada.
    #   2. Todos los servicios tienen total calculado.
    # Usa SAVEPOINT para rollback parcial en caso de error.
    _safe("""
        CREATE OR REPLACE PROCEDURE sp_cerrar_orden(
            p_ord_id IN NUMBER,
            p_mensaje OUT VARCHAR2
        )
        IS
            v_status VARCHAR2(50);
            v_pendientes NUMBER;
        BEGIN
            SAVEPOINT sp_save;

            SELECT ord_status INTO v_status FROM "Orders" WHERE ord_id = p_ord_id;
            IF v_status = 'CERRADA' THEN
                p_mensaje := 'La orden ya está cerrada';
                RETURN;
            END IF;

            SELECT COUNT(*) INTO v_pendientes
            FROM "ServiceOrders"
            WHERE ord_id = p_ord_id AND ords_total IS NULL;

            IF v_pendientes > 0 THEN
                p_mensaje := 'Hay servicios sin total calculado';
                ROLLBACK TO sp_save;
                RETURN;
            END IF;

            UPDATE "Orders" SET ord_status = 'CERRADA' WHERE ord_id = p_ord_id;
            COMMIT;
            p_mensaje := 'Orden cerrada exitosamente';
        EXCEPTION
            WHEN OTHERS THEN
                ROLLBACK TO sp_save;
                p_mensaje := SQLERRM;
                RAISE;
        END sp_cerrar_orden;
    """)

    # --- Vista: vw_resumen_clientes ---
    # Muestra para cada cliente: total de vehículos, total de órdenes
    # y cantidad de órdenes cerradas.
    _safe("""
        CREATE OR REPLACE VIEW vw_resumen_clientes AS
        SELECT c.cli_id, c.cli_name,
               (SELECT COUNT(*) FROM "Vehicles" v WHERE v.cli_id = c.cli_id) total_vehiculos,
               COUNT(o.ord_id) total_ordenes,
               SUM(CASE WHEN o.ord_status = 'CERRADA' THEN 1 ELSE 0 END) ordenes_cerradas
        FROM "Clients" c
        LEFT JOIN "Orders" o ON o.veh_id IN (SELECT veh_id FROM "Vehicles" v2 WHERE v2.cli_id = c.cli_id)
        GROUP BY c.cli_id, c.cli_name
    """)

    # --- Vista: vw_ordenes_activas ---
    # Muestra solo las órdenes que están abiertas o en proceso
    # (excluye órdenes cerradas). Útil para el panel de trabajo diario.
    _safe("""
        CREATE OR REPLACE VIEW vw_ordenes_activas AS
        SELECT ord_id, veh_id, ord_status, ord_date, ord_urgency
        FROM "Orders"
        WHERE ord_status IN ('ABIERTA', 'EN_PROCESO')
    """)

    # --- Vista materializada: vm_metricas_taller ---
    # Agrega órdenes por día para métricas de rendimiento.
    # Se refresca bajo demanda (BUILD IMMEDIATE, REFRESH COMPLETE ON DEMAND).
    _safe("""
        CREATE MATERIALIZED VIEW vm_metricas_taller
        BUILD IMMEDIATE
        REFRESH COMPLETE ON DEMAND
        AS
        SELECT TRUNC(ord_date) dia,
               COUNT(*) total_ordenes,
               SUM(CASE WHEN ord_status = 'CERRADA' THEN 1 ELSE 0 END) cerradas
        FROM "Orders"
        GROUP BY TRUNC(ord_date)
    """)

    # --- Triggers de auditoría: asignan ses_id automáticamente ---
    # Antes de INSERT en cada tabla, si ses_id es NULL, se asigna
    # el CLIENT_IDENTIFIER (seteado por Python vía DBMS_SESSION.SET_IDENTIFIER).
    # NOTA: \\:NEW escapa los dos puntos para que SQLAlchemy text()
    # no los interprete como bind variables.
    # NOTA2: NO usar SYS_CONTEXT('USERENV','SESSIONID') porque ese valor
    # es el ID de sesión de Oracle y NO existe como registro en Sessions.
    triggers = [
        ("trg_clients_ses_id", "Clients"),
        ("trg_vehicles_ses_id", "Vehicles"),
        ("trg_orders_ses_id", "Orders"),
        ("trg_serviceorders_ses_id", "ServiceOrders"),
        ("trg_service_ses_id", "Service"),
        ("trg_users_ses_id", "users"),
    ]
    for trg_name, tbl_name in triggers:
        _safe(f'''
            CREATE OR REPLACE TRIGGER {trg_name}
            BEFORE INSERT ON "{tbl_name}"
            FOR EACH ROW
            BEGIN
                IF \\:NEW.ses_id IS NULL THEN
                    \\:NEW.ses_id := TO_NUMBER(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'));
                END IF;
            END {trg_name};
        ''')

    # --- Trigger compuesto: TRG_VALIDAR_CIERRE_ORDEN ---
    # Valida que al cambiar ord_status a 'CERRADA', todos los
    # servicios de la orden tengan total calculado.
    # Es COMPOUND TRIGGER: captura los ord_id en BEFORE EACH ROW
    # y valida en AFTER STATEMENT (para operaciones bulk).
    # Si hay servicios sin total, lanza RAISE_APPLICATION_ERROR.
    _safe("""
        CREATE OR REPLACE TRIGGER "TRG_VALIDAR_CIERRE_ORDEN"
        FOR UPDATE OF ord_status ON "Orders"
        COMPOUND TRIGGER
            TYPE ord_id_tab IS TABLE OF "Orders".ord_id%TYPE;
            v_ord_ids ord_id_tab := ord_id_tab();

            BEFORE EACH ROW IS
            BEGIN
                IF \\:NEW.ord_status = 'CERRADA' AND \\:OLD.ord_status != 'CERRADA' THEN
                    v_ord_ids.EXTEND;
                    v_ord_ids(v_ord_ids.LAST) := \\:NEW.ord_id;
                END IF;
            END BEFORE EACH ROW;

            AFTER STATEMENT IS
                v_pendientes NUMBER;
            BEGIN
                FOR i IN 1..v_ord_ids.COUNT LOOP
                    SELECT COUNT(*) INTO v_pendientes
                    FROM "ServiceOrders"
                    WHERE ord_id = v_ord_ids(i) AND ords_total IS NULL;
                    IF v_pendientes > 0 THEN
                        RAISE_APPLICATION_ERROR(-20001,
                            'No se puede cerrar la orden ' || v_ord_ids(i) ||
                            ' tiene ' || v_pendientes || ' servicio(s) sin total');
                    END IF;
                END LOOP;
            END AFTER STATEMENT;
        END "TRG_VALIDAR_CIERRE_ORDEN";
    """)




def downgrade() -> None:
    # Elimina todos los objetos PL/SQL en orden inverso al de creación.
    # Primero triggers (dependen de tablas), luego vistas, luego procedures/functions, luego tabla.
    _safe('DROP TRIGGER "TRG_VALIDAR_CIERRE_ORDEN"')
    _safe('DROP TRIGGER trg_users_ses_id')
    _safe('DROP TRIGGER trg_service_ses_id')
    _safe('DROP TRIGGER trg_serviceorders_ses_id')
    _safe('DROP TRIGGER trg_orders_ses_id')
    _safe('DROP TRIGGER trg_vehicles_ses_id')
    _safe('DROP TRIGGER trg_clients_ses_id')
    _safe('DROP MATERIALIZED VIEW vm_metricas_taller')
    _safe('DROP VIEW vw_ordenes_activas')
    _safe('DROP VIEW vw_resumen_clientes')
    _safe('DROP PROCEDURE sp_cerrar_orden')
    _safe('DROP FUNCTION fn_calcular_total_orden')
    _safe('DROP FUNCTION fn_tiene_permiso')
    _safe('DROP TABLE permisos_rol CASCADE CONSTRAINTS')